moderator/settings.py

Add django-csp to project.

---

moderator/settings.py

Use Django's PBKDF2+bcrypt for password hashing.

---

moderator/moderate/templates/base.jinja

Fix tabzilla rendering

---

moderator/moderate/models.py
moderator/moderate/views.py

* Fix pep8 errors.
* Remove __unicode__ method.

Minor fixes.

---

moderator/settings.py
requirements/prod.txt

Bump oidc version to 0.1.9.

---

moderator/settings.py
requirements/prod.txt

* Temporarily disable logout from OP.

Bump oidc version.

---

moderator/moderate/static/css/main.css
moderator/moderate/templates/base.jinja

Use a button instead of a link for logging out.

---

moderator/moderate/views.py

* Raise a 404 if a user tries to view an non-existing event.

Fix regression about editing an event by all users.

---

Dockerfile

Update mysqlclient dependency.

---

moderator/moderate/static/css/main.css

fixes #256 - Fixes text selection in reply note

---

kubernetes/prod/deployment.yaml

Reverts mozilla/mozmoderator#271

Revert "Upgrade prod: people.m.o as Auth backend"

---

kubernetes/prod/deployment.yaml

Reverts mozilla/mozmoderator#272

Revert "Revert "Upgrade prod: people.m.o as Auth backend""

---

moderator/moderate/models.py
moderator/moderate/templates/questions.jinja
moderator/moderate/views.py

* Show questions in a random order
* Admins can see votes

Show votes when an event is archived.

---

moderator/moderate/forms.py
moderator/moderate/templates/create_event.jinja
moderator/moderate/templates/index.jinja
moderator/moderate/views.py

… edit events
update UI to reflect these changes

only allow superusers to create moderated events, allow moderators to edit events

---

.github/workflows/test.yaml

Testing something wrt managing secrets on public repos using GHA where PR forks can arise, ignore / will revert. Doesn't touch anything to do with deployment.

testing pull_request_target event for GHA

---

.github/workflows/cd.yaml

Jira: https://mozilla-hub.atlassian.net/browse/SE-2244

add stage & release (prod) tag prepare

---

.github/workflows/cd.yaml

Jira: https://mozilla-hub.atlassian.net/browse/SE-2244
What this PR does: still working out GHA tag setting for prod vs stage

revisit tag

---

.github/workflows/cd.yaml

Jira: https://mozilla-hub.atlassian.net/browse/SE-2244

one more revisit on GHA image tag generation

---

.github/workflows/cd.yaml

Jira ticket: https://mozilla-hub.atlassian.net/browse/SE-2244

change pipeline & conditional to use released event

---

moderator/moderate/views.py

Show questions sorted by votes when an event has closed.

---

moderator/moderate/models.py

* Added Accepted (True), Rejected (False) and Pending (None) as choices for boolean 'Is accepted'

394 - Add verbose choices to 'Is Accepted'

---

moderator/moderate/templates/questions.jinja

Added `aria-label` attributes to Upvote and Downvote/Un-vote buttons and the Answer dialog toggle to improve accessibility of the page

Update questions.jinja to add aria-labels for image buttons

---

moderator/moderate/static/css/main.css

Improving color contrast to ensure the content is more readable as well as adding an underline to link elements to visually communicate their interactivity for users.

Update main.css to improve accessibility of the page

---

moderator/moderate/templates/includes/profiles.html
moderator/moderate/templates/moderation.jinja
moderator/moderate/templates/questions.jinja

Fix 500 error on anonymous profiles.

---

moderator/moderate/auth.py
moderator/moderate/models.py
moderator/moderate/templates/includes/profiles.html
moderator/settings.py

Update authentication scopes.

---

moderator/moderate/static/css/main.css
moderator/moderate/static/js/app.js
moderator/moderate/templates/questions.jinja

Always have thumbs up, only change colors
Add tooltip (title) to vote buttons

Update buttons to color code on vote status
